In [1]:
! pip install numpy


   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.6 MB 8.6 MB/s eta 0:00:02
   ------------ --------------------------- 3.9/12.6 MB 11.2 MB/s eta 0:00:01
   ------------------------ --------------- 7.6/12.6 MB 14.1 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.6 MB 15.7 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 14.7 MB/s eta 0:00:00



[notice] A new release of pip is available: 24.2 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

print("successfully installed")

successfully installed


In [4]:
print(np.__version__)

2.2.5


In [ ]:
# # Array and list

# Array similar data store krte hai 
# array >>>>> [1,2,3,4,5,6]

# List >>>> [1,2,3,4,"kapil"] >>>>> list are used to store diffrent data types


In [7]:
lst = [1,2,3,4,5]
print("type of list:-",type(lst))
arr = np.array(lst)
print(arr)
print(type(arr))

type of list:- <class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [11]:
lst = list(range(1,20))
print(lst)
print(type(lst))

arr = np.array(lst)
print(arr)
print(type(arr))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
<class 'list'>
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>


In [12]:
arr = np.arange(1,20) # this function is used to create array
print(type(arr))

<class 'numpy.ndarray'>


In [13]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [18]:
arr = np.zeros((5,10))
arr


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
arr = np.ones((5,10))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### 1D array convert into 2D array

In [26]:
arr = np.arange(0,30)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [31]:
arr = np.random.random((5,10))
arr

array([[0.10631088, 0.61531994, 0.40946022, 0.83914015, 0.57099124,
        0.27925964, 0.90672282, 0.73165155, 0.74823345, 0.45382134],
       [0.27622215, 0.06038911, 0.31271197, 0.68575638, 0.63333729,
        0.88036985, 0.61842771, 0.05738362, 0.99561726, 0.06848144],
       [0.25487777, 0.96967965, 0.05978817, 0.98537153, 0.54728514,
        0.06300916, 0.43309099, 0.17115737, 0.5571385 , 0.45595045],
       [0.11733122, 0.3108836 , 0.69630526, 0.56506191, 0.84458264,
        0.97557467, 0.17842502, 0.55996629, 0.49351218, 0.87886364],
       [0.49215893, 0.83045135, 0.57340535, 0.25434402, 0.80434534,
        0.39683264, 0.33290737, 0.02404766, 0.3740559 , 0.64047761]])

In [32]:
arr.flatten()


array([0.10631088, 0.61531994, 0.40946022, 0.83914015, 0.57099124,
       0.27925964, 0.90672282, 0.73165155, 0.74823345, 0.45382134,
       0.27622215, 0.06038911, 0.31271197, 0.68575638, 0.63333729,
       0.88036985, 0.61842771, 0.05738362, 0.99561726, 0.06848144,
       0.25487777, 0.96967965, 0.05978817, 0.98537153, 0.54728514,
       0.06300916, 0.43309099, 0.17115737, 0.5571385 , 0.45595045,
       0.11733122, 0.3108836 , 0.69630526, 0.56506191, 0.84458264,
       0.97557467, 0.17842502, 0.55996629, 0.49351218, 0.87886364,
       0.49215893, 0.83045135, 0.57340535, 0.25434402, 0.80434534,
       0.39683264, 0.33290737, 0.02404766, 0.3740559 , 0.64047761])

In [33]:
arr.ravel()

array([0.10631088, 0.61531994, 0.40946022, 0.83914015, 0.57099124,
       0.27925964, 0.90672282, 0.73165155, 0.74823345, 0.45382134,
       0.27622215, 0.06038911, 0.31271197, 0.68575638, 0.63333729,
       0.88036985, 0.61842771, 0.05738362, 0.99561726, 0.06848144,
       0.25487777, 0.96967965, 0.05978817, 0.98537153, 0.54728514,
       0.06300916, 0.43309099, 0.17115737, 0.5571385 , 0.45595045,
       0.11733122, 0.3108836 , 0.69630526, 0.56506191, 0.84458264,
       0.97557467, 0.17842502, 0.55996629, 0.49351218, 0.87886364,
       0.49215893, 0.83045135, 0.57340535, 0.25434402, 0.80434534,
       0.39683264, 0.33290737, 0.02404766, 0.3740559 , 0.64047761])

In [34]:
arr.T

array([[0.10631088, 0.27622215, 0.25487777, 0.11733122, 0.49215893],
       [0.61531994, 0.06038911, 0.96967965, 0.3108836 , 0.83045135],
       [0.40946022, 0.31271197, 0.05978817, 0.69630526, 0.57340535],
       [0.83914015, 0.68575638, 0.98537153, 0.56506191, 0.25434402],
       [0.57099124, 0.63333729, 0.54728514, 0.84458264, 0.80434534],
       [0.27925964, 0.88036985, 0.06300916, 0.97557467, 0.39683264],
       [0.90672282, 0.61842771, 0.43309099, 0.17842502, 0.33290737],
       [0.73165155, 0.05738362, 0.17115737, 0.55996629, 0.02404766],
       [0.74823345, 0.99561726, 0.5571385 , 0.49351218, 0.3740559 ],
       [0.45382134, 0.06848144, 0.45595045, 0.87886364, 0.64047761]])

In [37]:
arr = np.arange(30)
arr
arr[11]

np.int64(11)

In [38]:
arr[0:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr[0] = 100
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [42]:
# 2D ARRAY
arr = np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [43]:
arr.reshape(10,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [55]:
arr[-1][-1]

IndexError: invalid index to scalar variable.

In [57]:
# 3D array

arr = np.array(np.arange(225).reshape(5,15,3))
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [58]:
arr[:,0,:]

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137],
       [180, 181, 182]])

In [59]:
arr[:,0:1,0:1]

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [63]:
arr[2][3][1] = 900000
arr

array([[[     0,      1,      2],
        [     3,      4,      5],
        [     6,      7,      8],
        [     9,     10,     11],
        [    12,     13,     14],
        [    15,     16,     17],
        [    18,     19,     20],
        [    21,     22,     23],
        [    24,     25,     26],
        [    27,     28,     29],
        [    30,     31,     32],
        [    33,     34,     35],
        [    36,     37,     38],
        [    39,     40,     41],
        [    42,     43,     44]],

       [[    45,     46,     47],
        [    48,     49,     50],
        [    51,     52,     53],
        [    54,     55,     56],
        [    57,     58,     59],
        [    60,     61,     62],
        [    63,     64,     65],
        [    66,     67,     68],
        [    69,     70,     71],
        [    72,     73,     74],
        [    75,     76,     77],
        [    78,     79,     80],
        [    81,     82,     83],
        [    84,     85,     86],
        [   

In [64]:
arr = np.array([2,3,4,1,5])

In [65]:
arr.sort()
arr

array([1, 2, 3, 4, 5])

In [66]:
arr*2


array([ 2,  4,  6,  8, 10])

In [67]:
arr-1

array([0, 1, 2, 3, 4])